---
- hosts: webservers
  become: yes
  tasks:
  - name: install webserver(apache2) on ubuntu14
    apt:
     name: "{{webserveronubunt}}"
     state: present
    when: ansible_os_family== "Debian"

  - name: start the service
    service:
     name: "{{webserveronubunt}}"
     state: started
    when: ansible_os_family== "Debian"

  