---
- hosts: webservers
  become: yes
  tasks:
  - name: i want to know host name
    command:  hostname -f
    register: myresult
  - name: display  myresult
    debug:
      msg: "{{myresult}}"


  - name: install webserver(apache2) on ubuntu14
    apt:
     name: "{{webserveronubuntu}}"
     state: present
    when: ansible_os_family== "Debian"

  - name: start the service
    service:
     name: "{{webserveronubuntu}}"
     state: started
    when: ansible_os_family== "Debian"

  