---
# tasks file for mytomrole---
# tasks file for mytominstall
- name: install tomcat
  apt:
   name: tomcat
   state: present

- name:  copy tom config file into all nodes
  template:
    src:  templates/mytomconfig.j2
    dest: /usr/share/tomcat/conf/tomcat.conf
  notify: starttomcat
- name:  Install Admin Packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - tomcat-webapps
    - tomcat-admin-webapps
- name: coy tom user file into all nodes
  template:
    src: templates/mytomuser.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restarttomcat
- name: i want to deploy ravi java war file into webapps  
  get_url: 
    url: http://13.233.164.0:8081/artifactory/manojkey/1/target/nareshLogin-1.0.war
    dest: /usr/share/tomcat/webapps/nareshLogin-1.0.war
    force_basic_auth: yes